### ISSUE TITLE
Tutorial broken when trying to add login functionality. 

### ISSUE THREAD

**Issue by gotoplanb** [stormpath/stormpath-ios-notes-example#3]
I add `Stormpath.sharedSession.login(emailTextField.text!, password: passwordTextField.text!, completionHandler: openNotes)
` to `login(_:)` as instructed in the tutorial.

Here is the error I see:

<img width="770" alt="screen shot 2016-11-04 at 5 18 54 pm" src="https://cloud.githubusercontent.com/assets/51855/20022839/ce7cedca-a2b2-11e6-9f18-11f9babcf41d.png">

For reference, here is my complete `LoginViewController.swift` file:

```
//
//  LoginViewController.swift
//  Stormpath Notes
//
//  Created by Edward Jiang on 3/11/16.
//  Copyright © 2016 Stormpath. All rights reserved.
//

import UIKit
import Stormpath

class LoginViewController: UIViewController {
    @IBOutlet weak var emailTextField: UITextField!
    @IBOutlet weak var passwordTextField: UITextField!
    
    
    @IBAction func login(_ sender: AnyObject) {
        // Code when someone presses the login button
        Stormpath.sharedSession.login(emailTextField.text!, password: passwordTextField.text!, completionHandler: openNotes)

    }
    
    @IBAction func loginWithFacebook(_ sender: AnyObject) {
        // Code when someone presses the login with Facebook button
        
    }
    
    @IBAction func loginWithGoogle(_ sender: AnyObject) {
        // Code when someone presses the login with Google button
        
    }

    @IBAction func resetPassword(_ sender: AnyObject) {
        // Code when someone presses the reset password button
        
    }
    
    func openNotes(_: Bool, _: NSError?) -> Void {
        func openNotes(success: Bool, error: NSError?) {
            if let error = error {
                showAlert(withTitle: "Error", message: error.localizedDescription)
            }
            else {
                performSegue(withIdentifier: "login", sender: self)
            }
        }
    }
}

// Helper extension to display alerts easily.
extension UIViewController {
    func showAlert(withTitle title: String, message: String?) {
        let alert = UIAlertController(title: title, message: message, preferredStyle: .alert)
        alert.addAction(UIAlertAction(title: "OK", style: .default, handler: nil))
        self.present(alert, animated: true, completion: nil)
    }
}

```

**Comment by edjiang** [comment]
Hey @gotoplanb! It looks like you've made a mistake in your `openNotes` function.

See how I've defined it in this finished example: 

https://github.com/stormpath/stormpath-ios-notes-example/blob/finished/Stormpath%20Notes/LoginViewController.swift

Thanks for reaching out!

**Comment by gotoplanb** [comment]
@edjiang I have the code working for the completed example, but the tutorial is still incorrect.

Tutorial says to use:

```
func openNotes(success: Bool, error: NSError?) {
    if let error = error {
        showAlert(withTitle: "Error", message: error.localizedDescription)
    }
    else {
        performSegueWithIdentifier("login", sender: self)
    }
}
```

but completed/working code example uses:

```
func openNotes(_ success: Bool, error: NSError?) {
        if let error = error {
            showAlert(withTitle: "Error", message: error.localizedDescription)
        }
        else {
            performSegue(withIdentifier: "login", sender: self)
        }
    }
```

There are two inconsistencies between the tutorial and the working code.

**Comment by gotoplanb** [comment]
I download the full/finished code from `master` and ran it locally. Notes either aren't POSTing or aren't GETting correctly, or else I'm just not understanding how the UI is supposed to respond. 

Please let me know what I'm missing. I'm trying to demonstrate Stormpath usage in a bootcamp with a gaggle of new iOS devs, and the tutorial isn't giving me a lot of confidence.

![stormpath](https://cloud.githubusercontent.com/assets/51855/20031917/0205162e-a356-11e6-921e-d42c409dcacc.gif)

**Comment by edjiang** [comment]
Gotcha. I'll fix it in the code example, since the tutorial code should be the more simpler and correct code. Both should work, however, based on how swift 3 treats closures now. 

As for the problems you're having now, I'll have to take a quick look. There were problems with Keychain in the 10.0 simulator, which prevented examples from working properly. I'm not sure about 10.1 simulator. I'll try it later today and correct the "finished" branch. 

If you're doing a tutorial on this, I'd be happy to spend some time chatting about this in a call. When is a good time for you? You can email me @ edward@stormpath.com. Thanks!

**Comment by edjiang** [comment]
OK, I've pushed an update to keep the code consistent with the tutorial. As I said, swift callbacks don't really care about the argument names as of Swift 3, so it's a minor change =]

As for your problem getting and saving the notes, this is because Stormpath saves your access token in the iOS Keychain. As mentioned in the tutorial, there is an iOS bug that prevents the Keychain from working properly in the simulator without workarounds. You can use the workaround suggested in this Stackoverflow post, run the code on a physical device, or use an older (iOS 9) simulator.

http://stackoverflow.com/a/40249263/1784384

Please do reach out to me about your workshop; I'd love to learn more about it, and see if there's any way I can help!
